//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DressExchangeServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dress_photo
    {
        public decimal dress_photo_id { get; set; }
        public decimal dress_id { get; set; }
        public string photo_location { get; set; }
        public byte[] photo_bytes { get; set; }
        public string photo_encoded { get; set; }
        public string dimensions { get; set; }
        public Nullable<System.DateTime> insert_datetime { get; set; }
        public string insert_user { get; set; }
        public string insert_process { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string update_user { get; set; }
        public string update_process { get; set; }
    
        public virtual dress dress { get; set; }
    }
}
