//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DressExchangeServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dress()
        {
            this.dress_photo = new HashSet<dress_photo>();
        }
    
        public decimal dress_id { get; set; }
        public decimal users_id { get; set; }
        public decimal size { get; set; }
        public string title { get; set; }
        public string condition { get; set; }
        public Nullable<System.DateTime> insert_datetime { get; set; }
        public string insert_user { get; set; }
        public string insert_process { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string update_user { get; set; }
        public string update_process { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dress_photo> dress_photo { get; set; }
        public virtual user user { get; set; }
    }
}
