//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DressExchangeServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class like
    {
        public decimal likes_id { get; set; }
        public decimal users_id { get; set; }
        public decimal liked_user_id { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
