//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DressExchangeServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.dresses = new HashSet<dress>();
            this.likes = new HashSet<like>();
            this.likes1 = new HashSet<like>();
        }
    
        public decimal users_id { get; set; }
        public string facebook_login { get; set; }
        public string email { get; set; }
        public string fullname { get; set; }
        public Nullable<decimal> size { get; set; }
        public decimal suburb_id { get; set; }
        public Nullable<System.DateTime> insert_datetime { get; set; }
        public string insert_user { get; set; }
        public string insert_process { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public string update_user { get; set; }
        public string update_process { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dress> dresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<like> likes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<like> likes1 { get; set; }
    }
}
